@extends('layouts.app')

@section('content')
    <div class="container p-4">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem veniam molestias unde enim reiciendis dolore delectus iste aliquid non? Accusamus laborum cumque, ex labore animi voluptates quaerat facere voluptate delectus!Accusamus, minima. Sed explicabo perferendis, voluptatem odio quasi dolores sit quia veniam magnam molestias nisi inventore culpa dolor. Placeat facere quis voluptatem sed quae natus fuga officia nobis, saepe animi.Possimus voluptatem dolores soluta, inventore quia dolore distinctio vero placeat, corrupti id porro! Nulla, quia tenetur at similique repudiandae nobis eos id eum dicta maiores, quam nemo sapiente mollitia neque.Corporis similique ea dignissimos deserunt quasi nihil saepe fuga assumenda. Totam, illo. Nemo possimus iste facilis ut? Sed, rerum repellat. Eligendi accusantium ex alias quo aut amet iusto architecto nobis.Veritatis porro qui libero fuga alias facere, ipsa aut dolores. Qui error quis consequatur, natus eaque fuga quibusdam. Pariatur, eligendi recusandae aliquam debitis rem placeat ad aspernatur soluta quae ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae autem neque totam maiores repellendus. Eaque quas atque odit, reiciendis ut at laborum. Quisquam incidunt veritatis laudantium aspernatur suscipit assumenda natus?Recusandae, est. Eum ducimus natus doloribus obcaecati atque quam numquam magni expedita enim, aperiam ipsum minus. Eveniet cupiditate est saepe sunt possimus suscipit deserunt itaque, obcaecati sit ipsum. Accusamus, recusandae.Fugiat nesciunt voluptatibus eveniet facere totam incidunt! Ut ab porro, cupiditate magnam vel tempore praesentium maiores cumque, nobis tempora possimus expedita itaque odit deleniti nostrum debitis totam modi sit libero!Fuga quod ratione numquam ut, aperiam repellat blanditiis voluptatibus. Repellendus nulla nihil veritatis, tempora quisquam consequatur, voluptatem illum eos voluptatibus incidunt, iure nostrum exercitationem! Minima delectus cumque iste ad quam!Unde tenetur ullam sequi consequuntur architecto sunt officiis molestiae non ex, dolore sit dicta veniam. Ex rem commodi nisi dolores temporibus in blanditiis similique, at fuga vel rerum minus sint.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ratione veritatis obcaecati deserunt ex ducimus, quas similique dolore corporis magni odio aut ad fuga placeat facere tempore ab eum rem saepe.Obcaecati cupiditate eligendi nihil quo ea nisi, esse sequi suscipit quos rem hic, excepturi soluta atque ratione aliquam dolor recusandae reprehenderit perferendis architecto facilis tempora nemo incidunt fuga. Nihil, quam?Possimus laboriosam nulla, voluptatum molestias unde animi ullam, error praesentium tempora quis recusandae nihil minima ex nesciunt corrupti fuga distinctio iste autem sed! Consectetur voluptate reiciendis perspiciatis, laborum consequatur aliquam!Assumenda cumque earum, adipisci sapiente natus, eveniet quo consequatur, asperiores quod libero provident blanditiis! Cumque error quibusdam impedit, esse quia est officia, cum debitis ut non nam aliquam? Dignissimos, cum.Ipsa fugit necessitatibus enim architecto, rem ex aliquid commodi deleniti ut molestias eum quod quisquam est fuga facilis nisi nulla nihil inventore vel. Saepe nesciunt adipisci suscipit voluptates est laborum.</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque sapiente odit beatae, nostrum aspernatur debitis nobis nihil consequuntur possimus minus dolor vero esse, distinctio deleniti vitae ipsam fugiat modi sequi.Quis blanditiis mollitia repellendus temporibus eos atque recusandae, voluptatibus commodi. Vitae vero, assumenda corporis tempora eius facilis magnam perspiciatis quae corrupti libero porro quos eveniet quaerat repudiandae a, amet ipsa.Corrupti, dolorum labore! Tenetur earum impedit aperiam, sunt vero deleniti beatae at illo veniam consequatur obcaecati. Adipisci asperiores ipsum, velit quis quibusdam culpa voluptatibus non ipsam quia, dicta dolore amet.Necessitatibus dolorem repellat deserunt cum sed quos laborum mollitia, libero voluptatem doloribus atque id deleniti velit omnis vel sequi. Modi autem laboriosam ipsum in pariatur facilis dolores tenetur dolor soluta!Laudantium iusto, rerum dolore incidunt sint eligendi fugiat recusandae voluptatibus minima sed dignissimos assumenda necessitatibus dolorum reprehenderit ea, quidem sapiente blanditiis, nesciunt rem. Ullam voluptatem pariatur, fugit nobis mollitia totam!</p>
    </div>
@endsection
